useDotenv: true

service: MangaApp

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 120

functions:
  healthcheck:
    handler: src/handlers/healthcheck.handler
    events:
      - http:
          path: /healthcheck
          # path: /healthcheck/{id} (defines path param)
          method: get
          # request:
          #   parameters:
          #     paths:
          #       deviceId: true (ture means required)
          #   querystrings:
          #     includeDeleted: false
          # bodyType: 'DeviceRequest' (body data type displays in swagger, defined in swagger type files)

          # The types to define swagger response
          responseData:
            '200':
              description: '200 response'
              bodyType: 'DummyResponse'
  createManga:
    handler: src/handlers/createManga.handler
    events:
      - http:
          path: /manga
          method: post
          cors:
            origin: '*'

  getManga:
    handler: src/handlers/getMangas.handler
    events:
      - http:
          path: /manga/{id}
          method: get
          cors:
            origin: '*'
      - http:
          path: /manga
          method: get
          cors:
            origin: '*'
  getChapter:
    handler: src/handlers/getChapters.handler
    events:
      - http:
          path: /chapter/{id}
          method: get
          cors:
            origin: '*'
  getCurrentPage:
    handler: src/handlers/getCurrentPage.handler
    events:
      - http:
          path: /page/{id}/current
          method: get
          cors:
            origin: '*'
  getNextPage:
    handler: src/handlers/getNextPage.handler
    events:
      - http:
          path: /page/{id}/next
          method: get
          cors:
            origin: '*'
  getPrevPage:
    handler: src/handlers/getPrevPage.handler
    events:
      - http:
          path: /page/{id}/prev
          method: get
          cors:
            origin: '*'
  getFirstPage:
    handler: src/handlers/getFirstPage.handler
    events:
      - http:
          path: /page/{id}/first
          method: get
          cors:
            origin: '*'
  createHistory:
    handler: src/handlers/createHistory.handler
    events:
      - http:
          path: /history/{chapterId}/{id}
          method: post
          cors:
            origin: '*'
  getHistory:
    handler: src/handlers/getHistory.handler
    events:
      - http:
          path: /history/{id}
          method: get
          cors:
            origin: '*'

custom:
  autoswagger:
    title: 'string'
    apiType: 'httpApi'
    generateSwaggerOnDeploy: true
    typefiles: ['./src/types/api-types.d.ts']
    swaggerFiles: []
    host: ${env:HOST_URL}
    basePath: '/dev'
    schemes: ['http', 'https']
    useRedirectUI: true
  static:
    folder: ./
    port: 5556
  serverless-offline:
    httpPort: 5555
    host: '0.0.0.0'

plugins:
  - serverless-auto-swagger
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-static
  - serverless-plugin-typescript

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - '!node_modules/prisma/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
